identified_parameters:
  Caf: 50040.604858819046
  Caf_freq: 0
  Car: 198123.38192755537
  Car_freq: 0
  Iz: 4913.081843914937
  Iz_combined: 2456.5409219574685
  Iz_freq: 0
  Kv: 0.009549309549969867
metadata:
  duration_seconds: 29217.016274690628
  scenario_counts:
    sine_sweep: 17003
    steady_state_cornering: 72361
    step_steer: 14052
  scenarios:
  - step_steer
  - sine_sweep
  - steady_state_cornering
  source_files:
  - 20250811_155411_step_steer.csv
  - 20250811_155525_step_steer.csv
  - 20250811_155759_step_steer.csv
  - 20250811_155918_step_steer.csv
  - 20250811_160301_step_steer.csv
  - 20250811_160504_sine_sweep.csv
  - 20250811_160659_sine_sweep.csv
  - 20250811_160922_sine_sweep.csv
  - 20250811_161120_sine_sweep.csv
  - 20250811_203728_steady_state_cornering.csv
  - 20250811_204715_steady_state_cornering.csv
  - 20250811_232550_steady_state_cornering.csv
  - 20250811_233110_steady_state_cornering.csv
  - 20250811_233432_steady_state_cornering.csv
  - 20250811_234008_steady_state_cornering.csv
  - 20250811_234345_steady_state_cornering.csv
  - 20250811_234647_steady_state_cornering.csv
  - 20250811_235159_steady_state_cornering.csv
  - 20250811_235831_steady_state_cornering.csv
  speed_range: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      AAAAQAF/9D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AQAA4CCuLEA=
  steering_range: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAQGZmOsA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAQGZmOkA=
  time_range: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      zo4W5mQm2kE=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      c5lXboEm2kE=
  total_samples: 103416
quality_metrics: {}
timestamp: '2025-08-12T00:13:09.639649'
validation_results:
  rmse_lateral_accel: 0.0
  rmse_yaw_rate: 0.0
  test_samples: 20684
vehicle_parameters:
  L: 3.0
  lf: 1.7
  lr: 1.3
  m: 1901.0
